### Get all Ads

GET http://localhost:3000/api/ads

### Get undefined path
GET http://localhost:3000/api/undefined

### Get single Ad
GET http://localhost:3000/api/ads/1

### Get undefined path
GET http://localhost:3000/api/ads/99