### Get all listings

GET http://localhost:3000/api/listings

### Get undefined path
GET http://localhost:3000/api/undefined

### Get single Listing
GET http://localhost:3000/api/listings/1

### Get undefined path
GET http://localhost:3000/api/listings/99

### Create Listing
POST http://localhost:3000/api/listings
Content-Type: application/json

{
    "title": "Test 3",
    "main_image_url": "https://www.google.com",
    "description": "Test 3",
    "price": 100,
    "phone": "123456789",
    "type": "sell",
    "town_id": 1,
    "user_id": 1,
    "category_id": 1
}

### Delete single Listing
DELETE  http://localhost:3000/api/listings/6


### Get all towns

GET http://localhost:3000/api/towns

### Get single town
GET http://localhost:3000/api/towns/1

### Get undefined path
GET http://localhost:3000/api/towns/99

### Create town
POST http://localhost:3000/api/towns
Content-Type: application/json

{
    "name": "Test 3",
    "population": 88888,
    "area": 9999
}

### Delete single town
DELETE  http://localhost:3000/api/towns/10

### Get all categories
GET http://localhost:3000/api/categories

### Get single category
GET http://localhost:3000/api/categories/1

### Get listings by category ID
GET http://localhost:3000/api/listings?category=1